<<<<<<< HEAD
# Generated by Django 3.2.9 on 2022-02-09 07:42
=======
# Generated by Django 3.2.11 on 2022-02-09 07:28
>>>>>>> 5c9f12b9b26329317c1aba1c47234defbdab9a83

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('judul', models.CharField(max_length=50)),
                ('caption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Informasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informasi', models.CharField(max_length=50)),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ormas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('unsur', models.CharField(max_length=50)),
                ('bidang', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=50)),
                ('desa', models.CharField(max_length=50)),
                ('kecamatan', models.CharField(max_length=50)),
                ('kabupaten', models.CharField(max_length=50)),
                ('namaNotaris', models.CharField(max_length=50)),
                ('noNotaris', models.CharField(max_length=50)),
                ('adArt', models.CharField(max_length=50)),
                ('sk', models.CharField(max_length=50)),
                ('masaBakti', models.CharField(max_length=50)),
                ('role', models.IntegerField(max_length=2)),
                ('biodataKetua', models.ImageField(null=True, upload_to='image/')),
                ('biodataSekretaris', models.ImageField(null=True, upload_to='image/')),
                ('biodataBendahara', models.ImageField(null=True, upload_to='image/')),
                ('status', models.CharField(default='0', max_length=1)),
<<<<<<< HEAD
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 5c9f12b9b26329317c1aba1c47234defbdab9a83
            ],
        ),
    ]
