# Generated by Django 3.2.9 on 2022-02-02 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ormas',
            old_name='user_id',
            new_name='user',
        ),
    ]
