# Generated by Django 4.0.1 on 2022-02-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ormas',
            name='role',
        ),
    ]
