# Generated by Django 3.2.9 on 2022-02-08 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0002_ormas_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ormas',
            name='user',
        ),
    ]
