# Generated by Django 3.2.9 on 2022-01-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0003_kabupaten_kecamatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsur', models.CharField(max_length=50)),
            ],
        ),
    ]
