# Generated by Django 3.2.9 on 2022-01-21 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0004_unsur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ormas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=50)),
                ('desa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eormasapp.desa')),
                ('kabupaten', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eormasapp.kabupaten')),
                ('kecamatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eormasapp.kecamatan')),
                ('unsur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eormasapp.unsur')),
            ],
        ),
    ]
