# Generated by Django 3.2.9 on 2022-01-21 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0005_ormas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ormas',
        ),
    ]
