# Generated by Django 3.2.9 on 2022-01-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0007_ormas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormas',
            name='desa',
            field=models.CharField(max_length=50),
        ),
    ]
