# Generated by Django 3.2.9 on 2022-01-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0008_alter_ormas_desa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Desa',
        ),
        migrations.AlterField(
            model_name='ormas',
            name='kabupaten',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ormas',
            name='kecamatan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ormas',
            name='unsur',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Kabupaten',
        ),
        migrations.DeleteModel(
            name='Kecamatan',
        ),
        migrations.DeleteModel(
            name='Unsur',
        ),
    ]
