# Generated by Django 3.2.9 on 2022-01-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0009_auto_20220122_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('judul', models.CharField(max_length=50)),
                ('caption', models.TextField()),
            ],
        ),
    ]
