# Generated by Django 3.2.9 on 2022-01-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0011_informasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormas',
            name='b',
            field=models.CharField(default='Review', max_length=7),
        ),
    ]
