# Generated by Django 3.2.9 on 2022-01-28 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0012_ormas_b'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ormas',
            old_name='b',
            new_name='action',
        ),
    ]
