# Generated by Django 3.2.11 on 2022-01-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0012_ormas_verifikasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormas',
            name='verifikasi',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
