# Generated by Django 3.2.9 on 2022-01-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0013_rename_b_ormas_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ormas',
            name='action',
        ),
        migrations.AddField(
            model_name='ormas',
            name='display',
            field=models.CharField(blank=True, choices=[('1', 'Review'), ('2', 'Accepted')], default='1', max_length=1, null=True),
        ),
    ]
