# Generated by Django 3.2.9 on 2022-01-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0016_alter_ormas_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormas',
            name='action',
            field=models.CharField(blank=True, choices=[('1', 'Review'), ('2', 'Accepted')], default='Review', max_length=10, null=True),
        ),
    ]
