# Generated by Django 3.2.9 on 2022-01-28 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0013_alter_ormas_verifikasi'),
        ('eormasapp', '0019_alter_ormas_action'),
    ]

    operations = [
    ]
