# Generated by Django 3.2.9 on 2022-01-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0020_merge_20220128_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ormas',
            name='action',
        ),
        migrations.AlterField(
            model_name='ormas',
            name='verifikasi',
            field=models.CharField(choices=[('Review', 'Review'), ('Accepted', 'Accepted')], default='Review', max_length=10),
        ),
    ]
