# Generated by Django 4.0.1 on 2022-01-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0020_merge_20220128_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ormas',
            name='action',
        ),
    ]
