# Generated by Django 3.2.9 on 2022-01-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0021_auto_20220128_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormas',
            name='verifikasi',
            field=models.CharField(choices=[('Review', 'Review'), ('Accepted', 'Accepted')], default='Review', max_length=50, null=True),
        ),
    ]
