# Generated by Django 3.2.9 on 2022-01-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0022_alter_ormas_verifikasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ormas',
            name='verifikasi',
        ),
        migrations.AddField(
            model_name='ormas',
            name='b',
            field=models.CharField(default='Review', editable=False, max_length=7),
        ),
    ]
