# Generated by Django 3.2.9 on 2022-01-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0023_auto_20220128_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ormas',
            name='b',
        ),
        migrations.AddField(
            model_name='ormas',
            name='verifikasi',
            field=models.CharField(default='Review', max_length=10),
        ),
    ]
