# Generated by Django 3.2.9 on 2022-01-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0024_auto_20220128_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormas',
            name='verifikasi',
            field=models.CharField(default='Review', max_length=50),
        ),
    ]
