# Generated by Django 3.2.9 on 2022-01-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0026_remove_ormas_verifikasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormas',
            name='status',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
