# Generated by Django 3.2.9 on 2022-01-30 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0015_alter_ormas_verifikasi'),
        ('eormasapp', '0021_remove_ormas_action'),
        ('eormasapp', '0027_ormas_status'),
    ]

    operations = [
    ]
