# Generated by Django 4.0.1 on 2022-01-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0015_alter_ormas_verifikasi'),
        ('eormasapp', '0021_remove_ormas_action'),
        ('eormasapp', '0027_ormas_status'),
    ]

    operations = [
    ]
