# Generated by Django 3.2.9 on 2022-01-31 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eormasapp', '0028_merge_20220130_1701'),
        ('eormasapp', '0028_merge_20220130_1926'),
    ]

    operations = [
    ]
